#+title: Short-Term Debt (Money) Markets 
#+author: Matt Brigida, Ph.D.
#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup
#+HTML_HEAD: <style>pre.src{background:#343131;color:white;} </style>
#+PROPERTY: header-args    :exports none

Money market securities are debt securities with a maturity of one year or less. Remembering the definition of /money/:

#+begin_example
Money is anything that (1) is a medium of exchange, and (2) a store of value.
#+end_example

We call them /money market/ securities because they function as money in the economy.  Because they have little interest rate risk they are a good /store of value/.

* Ask Llama2

#+begin_export html
<iframe src="https://ai-llama2-example.mdbrigida.workers.dev/" scrolling="no" frameborder="0" style="overflow:hidden; width:670px; height:525px;" allowTransparency="true" loading="lazy"></iframe>
#+end_export


* Specific Money Market Securities

** Treasury Bills (T Bills)

T Bills are short-term debt securities issued by the US Treasury.  You can read about t Bills here:  

** Repurchase Agreements (Repos)

Repos are the most important security that you have never heard of.  They are simply collateralized loans, however these loans can be very useful for managing cash and a firm's balance sheet.

*** Repo Use by the Fed

The Fed often uses repos to make short-term adjustments to monetary policy.  See the Fed's use of reverse repos in the chart below.  Note, a in a reverse repo you are just taking the other side of a repo---so you are buying an assets with an agreement to resell the asset at a set price.  So, the Fed uses reverse repos to temporarily increase the money supply.  In the chart below you can see the Fed temporarily increasing the money supply by over $2 trillion in from 2021 to 2024.

#+caption: Nominal Amount of Fed Reverse Repos
#+begin_export html
<iframe src="https://fred.stlouisfed.org/graph/graph-landing.php?g=1ibh6&width=670&height=475" scrolling="no" frameborder="0" style="overflow:hidden; width:670px; height:525px;" allowTransparency="true" loading="lazy"></iframe>
#+end_export

#+begin_export html
<br>
<br>
<br>
#+end_export

*** Repo 105

Repo 105 is an (extreme) example of how banks can use repos to manage their balance sheet.  Repo 105 was the name of the repo Lehman used to move poorly-performing assets off their balance sheet prior to taking the balance sheet snapshot.  Once the snapshot was taken, Lehman repurchased the bad assets.  [[https://en.wikipedia.org/wiki/Repo_105][See more here.]]
